dest_folder: /path/to/destination/folder
sample_count: 10
COEFFS:
  A1:
      - [0.5, 0.1, 0.2]
      - [0.1, 0.0, 0.1]
      - [0.1, 0.0, 0.2]
  A2:
      - [0.12, 0.0, 0.7]
      - [0.3, 0.1, 0.0]
      - [0.1, 0.0, 0.0]
INIT:
  - [1., 2., 3.]
  - [4., 5., 6.]